In [ ]:
import math
import numpy as np

In [ ]:
import math

# Using math.pi and math.e
print(f"Value of pi: {math.pi}")
print(f"Value of e: {math.e}")

# Using basic number-theoretic functions
print(f"Ceiling of 4.2: {math.ceil(4.2)}")
print(f"Floor of 4.9: {math.floor(4.9)}")
print(f"Absolute value of -10: {math.fabs(-10)}")
print(f"Factorial of 5: {math.factorial(5)}")
print(f"GCD of 48 and 18: {math.gcd(48, 18)}")
print(f"Square root of 25: {math.sqrt(25)}")


Value of pi: 3.141592653589793
Value of e: 2.718281828459045
Ceiling of 4.2: 5
Floor of 4.9: 4
Absolute value of -10: 10.0
Factorial of 5: 120
GCD of 48 and 18: 6
Square root of 25: 5.0


In [ ]:
import math

# Using power and logarithmic functions
print(f"2 to the power of 3: {math.pow(2, 3)}")
print(f"e to the power of 2: {math.exp(2)}")
print(f"Natural logarithm of 10: {math.log(10)}")
print(f"Base-10 logarithm of 100: {math.log10(100)}")

2 to the power of 3: 8.0
e to the power of 2: 7.38905609893065
Natural logarithm of 10: 2.302585092994046
Base-10 logarithm of 100: 2.0


In [ ]:
import math

# Using trigonometric functions (angles in radians)
angle_radians = math.radians(60)
print(f"Cosine of 60 degrees: {math.cos(angle_radians)}")
print(f"Sine of 60 degrees: {math.sin(angle_radians)}")
print(f"Tangent of 45 degrees: {math.tan(math.radians(45))}")

# Converting between degrees and radians
print(f"90 degrees in radians: {math.radians(90)}")
print(f"{math.pi} radians in degrees: {math.degrees(math.pi)}")

Cosine of 60 degrees: 0.5000000000000001
Sine of 60 degrees: 0.8660254037844386
Tangent of 45 degrees: 0.9999999999999999
90 degrees in radians: 1.5707963267948966
3.141592653589793 radians in degrees: 180.0


In [ ]:
import math

# Using angular conversion functions
print(f"atan2(1, 1): {math.atan2(1, 1)}") # Equivalent to atan(1/1)

# Using hyperbolic functions
print(f"Hyperbolic cosine of 0: {math.cosh(0)}")
print(f"Hyperbolic sine of 0: {math.sinh(0)}")
print(f"Hyperbolic tangent of 0: {math.tanh(0)}")
print(f"Inverse hyperbolic cosine of 1: {math.acosh(1)}")
print(f"Inverse hyperbolic sine of 0: {math.asinh(0)}")
print(f"Inverse hyperbolic tangent of 0: {math.atanh(0)}")

atan2(1, 1): 0.7853981633974483
Hyperbolic cosine of 0: 1.0
Hyperbolic sine of 0: 0.0
Hyperbolic tangent of 0: 0.0
Inverse hyperbolic cosine of 1: 0.0
Inverse hyperbolic sine of 0: 0.0
Inverse hyperbolic tangent of 0: 0.0


In [ ]:
math.sqrt(456)

21.354156504062622

In [ ]:
math.exp(10)

22026.465794806718

In [ ]:
math.exp2(10)

1024.0

In [ ]:
math.gcd(16,24)

8

In [ ]:

for i in range(65,91):
  print(chr(i),end=",")

A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,

In [ ]:
data=np.random.randint(1,100,(7,4))
data

array([[70, 59, 65,  6],
       [12, 92, 22, 44],
       [55, 88, 12, 39],
       [91, 62, 90, 19],
       [25, 34, 68, 28],
       [70, 38, 52, 38],
       [70, 43,  1, 26]])

In [ ]:
type(np.array(data))

numpy.ndarray

In [ ]:
print(data[-3:,-3:])
data[-3:-1,-3:-1]

[[34 68 28]
 [38 52 38]
 [43  1 26]]


array([[34, 68],
       [38, 52]])

In [ ]:
data[-2:-1,-2:-1]

array([[52]])

### 1. Homogeneous vs. Heterogeneous Data
This example shows that a NumPy array can only hold elements of the same data type, while a Python list can hold elements of different data types.

In [ ]:
import numpy as np

# NumPy array (homogeneous)
numpy_array = np.array([1, 2, 3, 4])
print("NumPy array:", numpy_array)
print("Data type of NumPy array elements:", numpy_array.dtype)

# Attempting to add a different data type to a NumPy array
# NumPy will try to find a common data type or raise an error
numpy_array_mixed = np.array([1, 'hello', 3.0])
print("NumPy array with mixed types:", numpy_array_mixed)
print("Data type of NumPy array with mixed types:", numpy_array_mixed.dtype)


# Python list (heterogeneous)
python_list = [1, 'hello', 3.0, True]
print("\nPython list:", python_list)

NumPy array: [1 2 3 4]
Data type of NumPy array elements: int64
NumPy array with mixed types: ['1' 'hello' '3.0']
Data type of NumPy array with mixed types: <U32

Python list: [1, 'hello', 3.0, True]


### 2. Performance
This example demonstrates the performance difference between NumPy arrays and Python lists for a simple arithmetic operation on a large number of elements.

In [ ]:
import time

# Using NumPy array
numpy_array_perf = np.arange(1000000)
start_time = time.time()
numpy_array_perf = numpy_array_perf * 2
end_time = time.time()
print(f"Time taken for NumPy array operation: {end_time - start_time:.6f} seconds")

# Using Python list
python_list_perf = list(range(1000000))
start_time = time.time()
python_list_perf = [x * 2 for x in python_list_perf]
end_time = time.time()
print(f"Time taken for Python list operation: {end_time - start_time:.6f} seconds")

Time taken for NumPy array operation: 0.006031 seconds
Time taken for Python list operation: 0.121415 seconds


### 3. Functionality
This example shows how NumPy provides built-in mathematical functions that operate on the entire array, which is not directly available for Python lists in the same way.

In [ ]:
# Using NumPy array
numpy_array_func = np.array([1, 2, 3, 4])
print("Original NumPy array:", numpy_array_func)
print("Square root of NumPy array elements:", np.sqrt(numpy_array_func))
print("Sum of NumPy array elements:", np.sum(numpy_array_func))

# Using Python list (requires looping or list comprehension for element-wise operations)
python_list_func = [1, 2, 3, 4]
print("\nOriginal Python list:", python_list_func)
# print("Square root of Python list elements:", math.sqrt(python_list_func)) # This would cause an error
print("Square root of Python list elements:", [math.sqrt(x) for x in python_list_func])
print("Sum of Python list elements:", sum(python_list_func))

Original NumPy array: [1 2 3 4]
Square root of NumPy array elements: [1.         1.41421356 1.73205081 2.        ]
Sum of NumPy array elements: 10

Original Python list: [1, 2, 3, 4]
Square root of Python list elements: [1.0, 1.4142135623730951, 1.7320508075688772, 2.0]
Sum of Python list elements: 10


***Fuctions in numpy ***

In [ ]:
data=np.random.randint(1,100,(7,4))
data

array([[69, 39, 36, 29],
       [ 5, 28, 32, 55],
       [80, 17, 51, 68],
       [ 6, 35, 86, 38],
       [ 5, 68,  9, 57],
       [49, 21,  2, 39],
       [62, 36, 13, 91]])

In [ ]:
# this is scalling of data-it is also called minmaix data or (normilize data)
data=np.array([1,2,3,4])
(data-data.min())/(data.max()-data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
List_2d=[[1,2,3],[4,5,6],[7,8,9]]
np.array(List_2d)
nparray=np.array(List_2d)
print(nparray)
print(nparray.shape)
print(nparray.ndim)
print(nparray.size)
#

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9


In [ ]:
List_3d=[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
np.array(List_3d)
print(np.array(List_3d).shape)


NameError: name 'np' is not defined

### `np.random.randint(low, high, size)`

This function generates random *integers* from `low` (inclusive) to `high` (exclusive). The `size` parameter specifies the shape of the output array.

In [ ]:
import numpy as np

# Example 1: Generate a single random integer between 0 and 10 (exclusive of 10)
random_integer = np.random.randint(0, 10)
print(f"Single random integer: {random_integer}")

# Example 2: Generate a 2x3 array of random integers between 50 and 100 (exclusive of 100)
random_integers_array = np.random.randint(50, 100, size=(2, 3))
print(f"\n2x3 array of random integers:\n{random_integers_array}")

Single random integer: 1

2x3 array of random integers:
[[99 63 88]
 [70 97 62]]


### `np.random.rand(d0, d1, ..., dn)`

This function generates random samples from a uniform distribution over ``[0, 1)``. The arguments `d0, d1, ..., dn` specify the dimensions of the output array.

In [ ]:
import numpy as np

# Example 1: Generate a single random float between 0 and 1
random_float = np.random.rand()
print(f"Single random float (uniform distribution): {random_float}")

# Example 2: Generate a 3x2 array of random floats between 0 and 1
random_floats_array = np.random.rand(3, 2)
print(f"\n3x2 array of random floats (uniform distribution):\n{random_floats_array}")

Single random float (uniform distribution): 0.45979206286020124

3x2 array of random floats (uniform distribution):
[[0.73395524 0.27211885]
 [0.42083002 0.46911727]
 [0.17257146 0.50861903]]


### `np.random.randn(d0, d1, ..., dn)`

This function generates random samples from the "standard normal" distribution (mean 0, variance 1). The arguments `d0, d1, ..., dn` specify the dimensions of the output array.

In [ ]:
import numpy as np

# Example 1: Generate a single random float from the standard normal distribution
random_normal_float = np.random.randn()
print(f"Single random float (standard normal distribution): {random_normal_float}")

# Example 2: Generate a 4-element 1D array of random floats from the standard normal distribution
random_normal_array = np.random.randn(4)
print(f"\n4-element array of random floats (standard normal distribution): {random_normal_array}")

Single random float (standard normal distribution): -0.3364910530065847

4-element array of random floats (standard normal distribution): [-0.22941881 -0.94639314  1.19528472  1.46846641]


In [ ]:
data=np.random.randint(1,100,(7,4))
data

array([[48, 79, 89, 22],
       [90, 84, 27, 71],
       [99, 69, 67, 26],
       [66, 69, 87, 40],
       [47, 66, 63, 22],
       [35,  4,  9, 42],
       [92, 92, 53, 76]])

In [ ]:
print(data)

[[48 79 89 22]
 [90 84 27 71]
 [99 69 67 26]
 [66 69 87 40]
 [47 66 63 22]
 [35  4  9 42]
 [92 92 53 76]]


In [ ]:
type(np.array(data))

numpy.ndarray

In [ ]:
print(data[0,0])
print(data[-3:,-3:])
print(data[-3:-1,-3:-1])
print(data[-2:,-3:])

48
[[66 63 22]
 [ 4  9 42]
 [92 53 76]]
[[66 63]
 [ 4  9]]
[[ 4  9 42]
 [92 53 76]]


In [ ]:
np.random.randint(0,100,(5,5))

array([[66, 37, 49, 96, 57],
       [46, 24, 51, 84, 94],
       [31, 55, 25, 22, 40],
       [83, 26, 41, 26, 93],
       [65, 91, 80, 35, 64]])

In [ ]:
np.random.rand(5,5)

array([[0.4004791 , 0.72193982, 0.99887021, 0.21250307, 0.2125227 ],
       [0.25961557, 0.00723068, 0.77711993, 0.3595405 , 0.42508319],
       [0.89233081, 0.10965526, 0.6404474 , 0.73326607, 0.57373938],
       [0.09657621, 0.555665  , 0.87419294, 0.20203824, 0.82101942],
       [0.97373125, 0.2028734 , 0.7807509 , 0.5647509 , 0.04832783]])