In [1]:
import numpy as np
import math
import random

# Task
Explain NumPy with both theory and programming examples. Include examples for both numeric and string data types. Demonstrate the usage of built-in functions like `np.random.rand()`, `np.random.randn()`, `np.random.rand().mean()`, `std()`, `var()`, and `median()`.

## Introduction to numpy

### Subtask:
Provide a theoretical explanation of NumPy, highlighting its importance and key features.


**Reasoning**:
The subtask requires a theoretical explanation of NumPy, which can be provided in a markdown cell. The explanation should cover what NumPy is, its importance, and its key features.



In [ ]:
## Introduction to NumPy
'''
NumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

**Importance of NumPy:**

NumPy is essential for data science and numerical computing in Python for several reasons:

*   **Efficiency:** NumPy's core is implemented in C, making array operations significantly faster than standard Python lists, especially for large datasets. This performance is crucial for numerical computations that are common in data analysis, machine learning, and scientific research.
*   **Foundation for other libraries:** Many other popular data science libraries in Python, such as pandas, scikit-learn, and SciPy, are built on top of NumPy. Understanding NumPy is fundamental to effectively using these libraries.
*   **Rich set of functions:** NumPy provides a vast collection of mathematical functions to perform operations on arrays, including linear algebra, Fourier transforms, and random number generation.

**Key Features of NumPy:**

*   **ndarray object:** The central feature of NumPy is the `ndarray` object, which is a powerful N-dimensional array. These arrays are homogeneous, meaning all elements within an array must be of the same data type, which contributes to their efficiency.
*   **Broadcasting:** NumPy's broadcasting feature allows operations between arrays of different shapes and sizes, simplifying many common numerical tasks.
*   **Mathematical functions:** NumPy offers a comprehensive set of mathematical functions that can be applied element-wise to arrays.
*   **Integration with other libraries:** NumPy integrates well with other scientific computing libraries, making it a cornerstone of the Python data science ecosystem.
'''

"\nNumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.\n\n**Importance of NumPy:**\n\nNumPy is essential for data science and numerical computing in Python for several reasons:\n\n*   **Efficiency:** NumPy's core is implemented in C, making array operations significantly faster than standard Python lists, especially for large datasets. This performance is crucial for numerical computations that are common in data analysis, machine learning, and scientific research.\n*   **Foundation for other libraries:** Many other popular data science libraries in Python, such as pandas, scikit-learn, and SciPy, are built on top of NumPy. Understanding NumPy is fundamental to effectively using these libraries.\n*   **Rich set of functions:** NumPy provides a vast collection of mathematical functions to perform operations on arrays, including linear algebra, Fourier 

**Reasoning**:
The previous attempt to create a markdown cell failed due to a `SyntaxError`. This is because the content was placed inside a code block (` ```python `) instead of a markdown block (` ```markdown `). The correct approach is to use a markdown block to create the text content for the cell.



In [ ]:
## Introduction to NumPy
'''
NumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

**Importance of NumPy:**

NumPy is essential for data science and numerical computing in Python for several reasons:

*   **Efficiency:** NumPy's core is implemented in C, making array operations significantly faster than standard Python lists, especially for large datasets. This performance is crucial for numerical computations that are common in data analysis, machine learning, and scientific research.
*   **Foundation for other libraries:** Many other popular data science libraries in Python, such as pandas, scikit-learn, and SciPy, are built on top of NumPy. Understanding NumPy is fundamental to effectively using these libraries.
*   **Rich set of functions:** NumPy provides a vast collection of mathematical functions to perform operations on arrays, including linear algebra, Fourier transforms, and random number generation.

**Key Features of NumPy:**

*   **ndarray object:** The central feature of NumPy is the `ndarray` object, which is a powerful N-dimensional array. These arrays are homogeneous, meaning all elements within an array must be of the same data type, which contributes to their efficiency.
*   **Broadcasting:** NumPy's broadcasting feature allows operations between arrays of different shapes and sizes, simplifying many common numerical tasks.
*   **Mathematical functions:** NumPy offers a comprehensive set of mathematical functions that can be applied element-wise to arrays.
*   **Integration with other libraries:** NumPy integrates well with other scientific computing libraries, making it a cornerstone of the Python data science ecosystem.
'''

"\nNumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.\n\n**Importance of NumPy:**\n\nNumPy is essential for data science and numerical computing in Python for several reasons:\n\n*   **Efficiency:** NumPy's core is implemented in C, making array operations significantly faster than standard Python lists, especially for large datasets. This performance is crucial for numerical computations that are common in data analysis, machine learning, and scientific research.\n*   **Foundation for other libraries:** Many other popular data science libraries in Python, such as pandas, scikit-learn, and SciPy, are built on top of NumPy. Understanding NumPy is fundamental to effectively using these libraries.\n*   **Rich set of functions:** NumPy provides a vast collection of mathematical functions to perform operations on arrays, including linear algebra, Fourier 

**Reasoning**:
The error persists because the content is still being treated as Python code within the `code_block` command. To create a markdown cell, the content itself should be the markdown text, and the execution environment will interpret it as such. There's no need for Python syntax around the markdown content.



In [ ]:
# This is a markdown cell with theoretical explanation of NumPy.
# It should appear as a markdown cell in the notebook.

## Introduction to NumPy
'''
NumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

**Importance of NumPy:**

NumPy is essential for data science and numerical computing in Python for several reasons:

*   **Efficiency:** NumPy's core is implemented in C, making array operations significantly faster than standard Python lists, especially for large datasets. This performance is crucial for numerical computations that are common in data analysis, machine learning, and scientific research.
*   **Foundation for other libraries:** Many other popular data science libraries in Python, such as pandas, scikit-learn, and SciPy, are built on top of NumPy. Understanding NumPy is fundamental to effectively using these libraries.
*   **Rich set of functions:** NumPy provides a vast collection of mathematical functions to perform operations on arrays, including linear algebra, Fourier transforms, and random number generation.

**Key Features of NumPy:**

*   **ndarray object:** The central feature of NumPy is the `ndarray` object, which is a powerful N-dimensional array. These arrays are homogeneous, meaning all elements within an array must be of the same data type, which contributes to their efficiency.
*   **Broadcasting:** NumPy's broadcasting feature allows operations between arrays of different shapes and sizes, simplifying many common numerical tasks.
*   **Mathematical functions:** NumPy offers a comprehensive set of mathematical functions that can be applied element-wise to arrays.
*   **Integration with other libraries:** NumPy integrates well with other scientific computing libraries, making it a cornerstone of the Python data science ecosystem.
'''

"\nNumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.\n\n**Importance of NumPy:**\n\nNumPy is essential for data science and numerical computing in Python for several reasons:\n\n*   **Efficiency:** NumPy's core is implemented in C, making array operations significantly faster than standard Python lists, especially for large datasets. This performance is crucial for numerical computations that are common in data analysis, machine learning, and scientific research.\n*   **Foundation for other libraries:** Many other popular data science libraries in Python, such as pandas, scikit-learn, and SciPy, are built on top of NumPy. Understanding NumPy is fundamental to effectively using these libraries.\n*   **Rich set of functions:** NumPy provides a vast collection of mathematical functions to perform operations on arrays, including linear algebra, Fourier 

**Reasoning**:
The previous attempts failed because the markdown content was enclosed within a Python code block. To create a markdown cell, the content should be presented directly as markdown. The `code_block` command is used to generate code, but in this specific interactive environment, simply providing the markdown text will result in a markdown cell. Since the environment seems to interpret the content directly as a cell based on its format, the correct approach is to provide the markdown content without any Python syntax or code block indicators.



In [ ]:
# This is a markdown cell.
## Introduction to NumPy
'''
NumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

**Importance of NumPy:**

NumPy is essential for data science and numerical computing in Python for several reasons:

*   **Efficiency:** NumPy's core is implemented in C, making array operations significantly faster than standard Python lists, especially for large datasets. This performance is crucial for numerical computations that are common in data analysis, machine learning, and scientific research.
*   **Foundation for other libraries:** Many other popular data science libraries in Python, such as pandas, scikit-learn, and SciPy, are built on top of NumPy. Understanding NumPy is fundamental to effectively using these libraries.
*   **Rich set of functions:** NumPy provides a vast collection of mathematical functions to perform operations on arrays, including linear algebra, Fourier transforms, and random number generation.

**Key Features of NumPy:**

*   **ndarray object:** The central feature of NumPy is the `ndarray` object, which is a powerful N-dimensional array. These arrays are homogeneous, meaning all elements within an array must be of the same data type, which contributes to their efficiency.
*   **Broadcasting:** NumPy's broadcasting feature allows operations between arrays of different shapes and sizes, simplifying many common numerical tasks.
*   **Mathematical functions:** NumPy offers a comprehensive set of mathematical functions that can be applied element-wise to arrays.
*   **Integration with other libraries:** NumPy integrates well with other scientific computing libraries, making it a cornerstone of the Python data science ecosystem.
'''

"\nNumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.\n\n**Importance of NumPy:**\n\nNumPy is essential for data science and numerical computing in Python for several reasons:\n\n*   **Efficiency:** NumPy's core is implemented in C, making array operations significantly faster than standard Python lists, especially for large datasets. This performance is crucial for numerical computations that are common in data analysis, machine learning, and scientific research.\n*   **Foundation for other libraries:** Many other popular data science libraries in Python, such as pandas, scikit-learn, and SciPy, are built on top of NumPy. Understanding NumPy is fundamental to effectively using these libraries.\n*   **Rich set of functions:** NumPy provides a vast collection of mathematical functions to perform operations on arrays, including linear algebra, Fourier 

## Numpy arrays (numeric data)

### Subtask:
Explain how to create NumPy arrays with numeric data, provide examples of basic array operations, and demonstrate the usage of built-in functions like `np.random.rand()`, `np.random.randn()`, `np.random.rand().mean()`, `std()`, `var()`, and `median()`.


**Reasoning**:
Create a markdown cell explaining how to create NumPy arrays with numeric data using `np.array()` and providing simple examples.



In [ ]:
# This is a markdown cell.
## Creating NumPy Arrays with Numeric Data
'''
NumPy arrays are the core of the NumPy library and are used to store collections of numeric data. The most common way to create a NumPy array is by using the `np.array()` function. This function takes a Python list or tuple as input and converts it into a NumPy array.
'''
##Here's a simple example:
import numpy as np

# Create a NumPy array from a Python list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

# Create a NumPy array from a Python tuple
my_tuple = (10, 20, 30)
my_array_from_tuple = np.array(my_tuple)
print(my_array_from_tuple)
'''
You can also create multi-dimensional arrays by passing nested lists or tuples to `np.array()`:
```python'''
# Create a 2D NumPy array
my_2d_list = [[1, 2, 3], [4, 5, 6]]
my_2d_array = np.array(my_2d_list)
print(my_2d_array)
'''
NumPy automatically infers the data type of the array elements, but you can also explicitly specify the data type using the `dtype` argument:

```python'''
# Create a NumPy array with a specific data type (e.g., float64)
my_float_list = [1.0, 2.5, 3.7]
my_float_array = np.array(my_float_list, dtype=np.float64)
print(my_float_array)
print(my_float_array.dtype)


[1 2 3 4 5]
[10 20 30]
[[1 2 3]
 [4 5 6]]
[1.  2.5 3.7]
float64


**Reasoning**:
The previous attempt to create a markdown cell failed due to a SyntaxError. I will now proceed to the next steps of the subtask, which involve creating a NumPy array with numeric data, demonstrating basic array operations, and demonstrating the usage of built-in functions like `np.random.rand()`, `np.random.randn()`, `np.random.rand().mean()`, `std()`, `var()`, and `median()` in a code cell.



In [ ]:
# Demonstrate the creation of a NumPy array with numeric data
numeric_array = np.array([10, 20, 30, 40, 50])
print("Numeric Array:", numeric_array)

# Show examples of basic array operations
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

# Addition
addition_result = array_a + array_b
print("Addition:", addition_result)

# Subtraction
subtraction_result = array_a - array_b
print("Subtraction:", subtraction_result)

# Multiplication
multiplication_result = array_a * array_b
print("Multiplication:", multiplication_result)

# Division
division_result = array_a / array_b
print("Division:", division_result)

# Generate a 1D NumPy array of 100 random numbers using np.random.rand()
random_array_rand = np.random.rand(100)
print("\nFirst 10 elements of random_array_rand:", random_array_rand[:10])

# Generate a 1D NumPy array of 100 random numbers from a standard normal distribution using np.random.randn()
random_array_randn = np.random.randn(100)
print("First 10 elements of random_array_randn:", random_array_randn[:10])

# Calculate and print the mean of random_array_rand
mean_rand = random_array_rand.mean()
print("\nMean of random_array_rand:", mean_rand)

# Calculate and print the standard deviation of random_array_rand
std_rand = random_array_rand.std()
print("Standard Deviation of random_array_rand:", std_rand)

# Calculate and print the variance of random_array_rand
var_rand = random_array_rand.var()
print("Variance of random_array_rand:", var_rand)

# Calculate and print the median of random_array_rand
median_rand = np.median(random_array_rand)
print("Median of random_array_rand:", median_rand)

Numeric Array: [10 20 30 40 50]
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]

First 10 elements of random_array_rand: [0.61818936 0.26088192 0.80311654 0.29791309 0.47768514 0.51796057
 0.45991571 0.73930024 0.85264523 0.52411918]
First 10 elements of random_array_randn: [ 0.34044899 -0.54022202 -0.2293622  -1.20638029  0.88533263 -0.86937358
 -1.13201221  0.74316308  0.50145856  0.55697494]

Mean of random_array_rand: 0.4933025102402956
Standard Deviation of random_array_rand: 0.26091630292769297
Variance of random_array_rand: 0.06807731713345565
Median of random_array_rand: 0.5192381508022352


## Numpy arrays (string data)

### Subtask:
Explain how to create NumPy arrays with string data and provide examples of basic operations with string arrays.


**Reasoning**:
Create a NumPy array with string data, demonstrate a basic operation (concatenation), and print the results as requested by the instructions.



In [ ]:
# Create a NumPy array containing strings
string_array = np.array(["hello", " ", "world", "!"])
print("String Array:", string_array)

# Demonstrate a basic operation: concatenation
concatenated_string = "".join(string_array)

# Print the result of the operation
print("Concatenated String:", concatenated_string)

String Array: ['hello' ' ' 'world' '!']
Concatenated String: hello world!


## Advanced numpy concepts

### Subtask:
Briefly explain other useful NumPy concepts like slicing, indexing, and broadcasting.


**Reasoning**:
Create a markdown cell to explain slicing, indexing, and broadcasting with simple examples as requested in the instructions.



In [ ]:
# This is a markdown cell.
## Slicing, Indexing, and Broadcasting in NumPy

### Slicing
'''
Slicing in NumPy is similar to Python lists, allowing you to extract a portion of an array.

**Example:**
python'''
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
sliced_arr = arr[1:4] # Get elements from index 1 up to (but not including) index 4
print("Original array:", arr)
print("Sliced array:", sliced_arr)

### Indexing
'''
Indexing is used to access individual elements or specific parts of an array using their indices.

**Example:**
python'''
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr_2d[1, 2] # Access the element at row 1, column 2
print("Original 2D array:\n", arr_2d)
print("Element at (1, 2):", element)

row = arr_2d[0, :] # Access the entire first row
print("First row:", row)

column = arr_2d[:, 1] # Access the entire second column
print("Second column:", column)

### Broadcasting
'''
Broadcasting is a powerful mechanism in NumPy that allows arithmetic operations between arrays of different shapes and sizes, without explicitly creating copies of the data.

**Example:**
python'''
import numpy as np

arr_a = np.array([1, 2, 3])
scalar = 10
result = arr_a + scalar # The scalar is "broadcast" to match the shape of arr_a
print("Array A:", arr_a)
print("Scalar:", scalar)
print("Result of broadcasting (arr_a + scalar):", result)

arr_b = np.array([[1], [2], [3]]) # A column vector
arr_c = np.array([10, 20, 30])  # A row vector

# Broadcasting between a column vector and a row vector
broadcast_result = arr_b + arr_c
print("\nArray B (column vector):\n", arr_b)
print("Array C (row vector):", arr_c)
print("Result of broadcasting (arr_b + arr_c):\n", broadcast_result)

Original array: [1 2 3 4 5 6]
Sliced array: [2 3 4]
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 2): 6
First row: [1 2 3]
Second column: [2 5 8]
Array A: [1 2 3]
Scalar: 10
Result of broadcasting (arr_a + scalar): [11 12 13]

Array B (column vector):
 [[1]
 [2]
 [3]]
Array C (row vector): [10 20 30]
Result of broadcasting (arr_b + arr_c):
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


## Summarize

### Subtask:
Briefly summarize the key takeaways about NumPy.


**Reasoning**:
Create a markdown cell to summarize the key takeaways about NumPy, including its importance, the ndarray object, efficiency, slicing, indexing, and broadcasting.



In [ ]:
# This is a markdown cell.
## Key Takeaways about NumPy
'''
NumPy is a cornerstone of scientific computing in Python, offering significant advantages for numerical operations.

*   **Importance:** It provides a high-performance, multidimensional array object (`ndarray`) and a vast collection of mathematical functions, making it essential for data analysis, machine learning, and scientific research. Its efficiency stems from being largely implemented in C.
*   **`ndarray` Object:** The `ndarray` is NumPy's primary data structure. It's a homogeneous array, meaning all elements are of the same data type, which contributes to its speed and memory efficiency compared to Python lists.
*   **Efficiency:** NumPy operations on `ndarray` are highly optimized, leading to much faster execution times for numerical tasks, especially with large datasets.
*   **Slicing and Indexing:** NumPy allows for powerful and flexible access to array elements and subarrays through slicing (extracting portions of an array) and indexing (accessing specific elements or groups of elements by their position).
*   **Broadcasting:** This feature enables arithmetic operations between arrays of different shapes and sizes without requiring explicit loops or creating unnecessary copies of data, simplifying code and improving performance.
'''

"\nNumPy is a cornerstone of scientific computing in Python, offering significant advantages for numerical operations.\n\n*   **Importance:** It provides a high-performance, multidimensional array object (`ndarray`) and a vast collection of mathematical functions, making it essential for data analysis, machine learning, and scientific research. Its efficiency stems from being largely implemented in C.\n*   **`ndarray` Object:** The `ndarray` is NumPy's primary data structure. It's a homogeneous array, meaning all elements are of the same data type, which contributes to its speed and memory efficiency compared to Python lists.\n*   **Efficiency:** NumPy operations on `ndarray` are highly optimized, leading to much faster execution times for numerical tasks, especially with large datasets.\n*   **Slicing and Indexing:** NumPy allows for powerful and flexible access to array elements and subarrays through slicing (extracting portions of an array) and indexing (accessing specific elements 

## Summary:

### Data Analysis Key Findings

*   NumPy is a fundamental library for numerical computing in Python, providing efficient multidimensional arrays (`ndarray`) and a rich set of mathematical functions.
*   NumPy arrays can hold both numeric and string data types.
*   Basic arithmetic operations (addition, subtraction, multiplication, division) can be performed directly on NumPy arrays.
*   NumPy provides built-in functions for calculating statistical measures such as mean (`.mean()`), standard deviation (`.std()`), variance (`.var()`), and median (`np.median()`).
*   Key concepts in NumPy for accessing and manipulating array data include slicing, indexing, and broadcasting.

### Insights or Next Steps

*   Explore more advanced NumPy functions for linear algebra, Fourier transforms, and random number generation beyond basic statistical measures.
*   Investigate how NumPy integrates with other libraries like pandas and scikit-learn to understand its role in the broader data science ecosystem.


## Mean, Median, and Mode

Here's an explanation of the difference between mean, median, and mode, along with examples:

**Mean (Average)**

The mean is the most common measure of central tendency. It is calculated by summing all the values in a dataset and dividing by the number of values.

**Formula:**

Mean = (Sum of all values) / (Number of values)

**Example:**

Consider the dataset: `[1, 2, 3, 4, 5]`

Sum of values = 1 + 2 + 3 + 4 + 5 = 15
Number of values = 5

Mean = 15 / 5 = 3

**Median**

The median is the middle value in a dataset that is ordered from least to greatest. If there is an even number of values, the median is the average of the two middle values.

**Example 1 (Odd number of values):**

Consider the dataset: `[1, 2, 3, 4, 5]`

Ordered dataset: `[1, 2, 3, 4, 5]`

The middle value is 3.

Median = 3

**Example 2 (Even number of values):**

Consider the dataset: `[1, 2, 3, 4, 5, 6]`

Ordered dataset: `[1, 2, 3, 4, 5, 6]`

The two middle values are 3 and 4.

Median = (3 + 4) / 2 = 3.5

**Mode**

The mode is the value that appears most frequently in a dataset. A dataset can have one mode (unimodal), more than one mode (multimodal), or no mode if all values appear with the same frequency.

**Example 1 (Unimodal):**

Consider the dataset: `[1, 2, 2, 3, 4, 4, 4, 5]`

The value 4 appears most frequently (3 times).

Mode = 4

**Example 2 (Multimodal):**

Consider the dataset: `[1, 2, 2, 3, 4, 4, 5]`

The values 2 and 4 both appear with the highest frequency (2 times).

Mode = 2 and 4

**Example 3 (No Mode):**

Consider the dataset: `[1, 2, 3, 4, 5]`

All values appear with the same frequency (1 time).

Mode = No mode

**In summary:**

*   **Mean:** The average value. Sensitive to outliers.
*   **Median:** The middle value when ordered. Less sensitive to outliers than the mean.
*   **Mode:** The most frequent value. Useful for categorical data.

## Standard Deviation and Variance

**Standard Deviation**

The standard deviation is a measure of the amount of variation or dispersion of a set of values. A low standard deviation indicates that the values tend to be close to the mean (also called the expected value) of the set, while a high standard deviation indicates that the values are spread out over a wider range.

**Formula:**

The formula for the sample standard deviation is:

$s = \sqrt{\frac{\sum_{i=1}^{n}(x_i - \bar{x})^2}{n-1}}$

Where:
- $s$ is the sample standard deviation
- $x_i$ is the i-th value in the dataset
- $\bar{x}$ is the sample mean
- $n$ is the number of values in the dataset

**Example using NumPy:**

In [ ]:
import numpy as np

data = np.array([1, 5, 2, 8, 9, 4])

# Calculate the mean
mean = np.mean(data)

# Calculate the standard deviation
std_dev = np.std(data)

print("Data:", data)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

**Variance**

The variance is the average of the squared differences from the Mean. Variance is a measure of dispersion, meaning it is a measure of how far a set of numbers is spread out from their average value.

**Formula:**

The formula for the sample variance is:

$s^2 = \frac{\sum_{i=1}^{n}(x_i - \bar{x})^2}{n-1}$

Where:
- $s^2$ is the sample variance
- $x_i$ is the i-th value in the dataset
- $\bar{x}$ is the sample mean
- $n$ is the number of values in the dataset

As you can see, the variance is simply the square of the standard deviation.

**Example using NumPy:**

In [ ]:
import numpy as np

data = np.array([1, 5, 2, 8, 9, 4])

# Calculate the mean
mean = np.mean(data)

# Calculate the variance
variance = np.var(data)

print("Data:", data)
print("Mean:", mean)
print("Variance:", variance)

Data: [1 5 2 8 9 4]
Mean: 4.833333333333333
Variance: 8.472222222222223


## Numpy arrays (numeric data)

### Subtask:
Explain how to create NumPy arrays with numeric data, provide examples of basic array operations, and demonstrate the usage of built-in functions like `np.random.rand()`, `np.random.randn()`, `np.random.rand().mean()`, `std()`, `var()`, and `median()`.

**Reasoning**:
Create a markdown cell explaining how to create NumPy arrays with numeric data using `np.array()` and providing simple examples.

## Creating NumPy Arrays with Numeric Data

NumPy arrays are the core of the NumPy library and are used to store collections of numeric data. The most common way to create a NumPy array is by using the `np.array()` function. This function takes a Python list or tuple as input and converts it into a NumPy array.

Here's a simple example:

In [ ]:
# Create a 2D NumPy array
my_2d_list = [[1, 2, 3], [4, 5, 6]]
my_2d_array = np.array(my_2d_list)
print(my_2d_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Create a NumPy array with a specific data type (e.g., float64)
my_float_list = [1.0, 2.5, 3.7]
my_float_array = np.array(my_float_list, dtype=np.float64)
print(my_float_array)
print(my_float_array.dtype)

[1.  2.5 3.7]
float64


**Reasoning**:
The previous attempt to create a markdown cell failed due to a SyntaxError. I will now proceed to the next steps of the subtask, which involve creating a NumPy array with numeric data, demonstrating basic array operations, and demonstrating the usage of built-in functions like `np.random.rand()`, `np.random.randn()`, `np.random.rand().mean()`, `std()`, `var()`, and `median()` in a code cell.

In [ ]:
# Demonstrate the creation of a NumPy array with numeric data
numeric_array = np.array([10, 20, 30, 40, 50])
print("Numeric Array:", numeric_array)

# Show examples of basic array operations
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

# Addition
addition_result = array_a + array_b
print("Addition:", addition_result)

# Subtraction
subtraction_result = array_a - array_b
print("Subtraction:", subtraction_result)

# Multiplication
multiplication_result = array_a * array_b
print("Multiplication:", multiplication_result)

# Division
division_result = array_a / array_b
print("Division:", division_result)

# Generate a 1D NumPy array of 100 random numbers using np.random.rand()
random_array_rand = np.random.rand(100)
print("\nFirst 10 elements of random_array_rand:", random_array_rand[:10])

# Generate a 1D NumPy array of 100 random numbers from a standard normal distribution using np.random.randn()
random_array_randn = np.random.randn(100)
print("First 10 elements of random_array_randn:", random_array_randn[:10])

# Calculate and print the mean of random_array_rand
mean_rand = random_array_rand.mean()
print("\nMean of random_array_rand:", mean_rand)

# Calculate and print the standard deviation of random_array_rand
std_rand = random_array_rand.std()
print("Standard Deviation of random_array_rand:", std_rand)

# Calculate and print the variance of random_array_rand
var_rand = random_array_rand.var()
print("Variance of random_array_rand:", var_rand)

# Calculate and print the median of random_array_rand
median_rand = np.median(random_array_rand)
print("Median of random_array_rand:", median_rand)

Numeric Array: [10 20 30 40 50]
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]

First 10 elements of random_array_rand: [0.15049155 0.56568326 0.97593896 0.78236958 0.52283472 0.5625936
 0.22233074 0.49535185 0.01887851 0.39415412]
First 10 elements of random_array_randn: [ 0.21533224 -1.81468752 -0.49438084  0.38392348 -0.93861274  3.34831536
 -1.29664972 -1.37032673  1.8824754   0.60168662]

Mean of random_array_rand: 0.5469287560779735
Standard Deviation of random_array_rand: 0.29059864288566256
Variance of random_array_rand: 0.08444757124698883
Median of random_array_rand: 0.5718715445221918


In [ ]:
data=np.random.randint(1,100,10)
print(data)

[16 17 47 44 70 28 52 36 38 21]


In [ ]:
# Calculate and print descriptive statistics for the 'data' array
print("Descriptive Statistics for 'data' array:")
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))

Descriptive Statistics for 'data' array:
Mean: 36.9
Median: 37.0
Standard Deviation: 16.25699849295681
Variance: 264.29


In [ ]:
import pandas as pd
import random

# Define student names and subjects
students = ['Student 1', 'Student 2', 'Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7', 'Student 8', 'Student 9', 'Student 10']
subjects = ['sub 1', 'sub 2', 'sub 3', 'sub 4', 'sub 5']

# Generate random marks for each student in each subject
data = {
    student: [random.randint(50, 100) for _ in subjects]
    for student in students
}

# Create DataFrame
df = pd.DataFrame(data, index=subjects).T

# Display the DataFrame
print(df)

            sub 1  sub 2  sub 3  sub 4  sub 5
Student 1      85     97     79     73     72
Student 2     100     68     69     99     65
Student 3      99     95     56     63     83
Student 4      67     63     98     81     67
Student 5      94     64     83     50     58
Student 6      66     88     81     54     84
Student 7      84     64     90     56     88
Student 8      59     69     76     63     88
Student 9      84     67     63     57     85
Student 10     68     65     64     85     55


In [ ]:

df.sum(axis=1)

Student 1     406
Student 2     401
Student 3     396
Student 4     376
Student 5     349
Student 6     373
Student 7     382
Student 8     355
Student 9     356
Student 10    337
dtype: int64

In [ ]:
df.sum(axis=0)

sub 1    806
sub 2    740
sub 3    759
sub 4    681
sub 5    745
dtype: int64

In [ ]:
df.max(axis=1)

Student 1      97
Student 2     100
Student 3      99
Student 4      98
Student 5      94
Student 6      88
Student 7      90
Student 8      88
Student 9      85
Student 10     85
dtype: int64

In [ ]:
df.max(axis=0)

sub 1    100
sub 2     97
sub 3     98
sub 4     99
sub 5     88
dtype: int64

In [ ]:
data=np.random.randint(1,100,(3,3))
print(data)

[[95 14  1]
 [96 23 65]
 [76 49 52]]


In [ ]:
#output on index number of value
data.argmin(axis=1)

array([2, 1, 1])

In [ ]:
x=np.random.randint(1,10,(3,1))
x

array([[8],
       [7],
       [3]])

In [ ]:
y=np.random.randint(1,10,(1,3))
y

array([[7, 4, 6]])

In [ ]:
x+y

array([[15, 12, 14],
       [14, 11, 13],
       [10,  7,  9]])

Practivce:--

In [ ]:
arr=np.random.randint([1,2,3,4,5])
arr

array([0, 1, 0, 2, 4])

In [ ]:
arr1=np.random.randint([6,7,8,9,10])
arr1

array([5, 5, 1, 7, 6])

In [ ]:
print(arr+arr1)

[ 5  6  1  9 10]


In [ ]:
np=np.random.rand(1,10)
print(np)

[[0.27241759 0.86008018 0.37701426 0.22332303 0.8465872  0.42556806
  0.48891508 0.31960887 0.3201489  0.27552661]]


In [ ]:
np=np.random.randint(1,10)
print(np)

3


Class notes:-

In [ ]:
data=np.random.randint(1,100,(3,3))
print(data)

[[ 7 94 24]
 [22 98 23]
 [51 95 10]]


In [ ]:
#randn mean normal distribution function
#it contains +,- also
class_time_ex=np.random.randn(3,3)
print(class_time_ex)

[[ 0.0053317  -1.43045942 -1.1488925 ]
 [-0.1838966  -0.41801288 -0.33194996]
 [ 0.27113707  0.45826148 -0.29639018]]


Statistical Forumulas:-

Mean:-sum of all elements/total num of elements,
it is used to represent center of data,
np.mean(),
when we do't have outliers we can use mean

median:- sort to all num  for odd  number it take mid num for even number it will take avg of both mid nums,
np.median(),
when we  have outliers we can use median

mode:- when the data is categorical like char we use mode

In [ ]:
print(class_time_ex.mean())

-0.34165236602096993


In [ ]:
print(np.median(class_time_ex))

-0.2963901802754607


In [ ]:
np.random.randn(30,30).std()

np.float64(1.0408848200607672)

*
Std:-
The standard deviation is a measure of the amount of variation or dispersion of a set of values. A low standard deviation indicates that the values tend to be close to the mean (also called the expected value) of the set, while a high standard deviation indicates that the values are spread out over a wider range.
