In [3]:
import numpy as np
import math
import random

np.eye(),np.arange(),np.zeros(),np.ones(),
np.lineinch(),

In [ ]:
data=np.random.randint(0,10,(4,4))
data

array([[8, 7, 3, 3],
       [9, 0, 2, 5],
       [9, 9, 9, 6],
       [3, 9, 9, 1]])

In [ ]:
print(np.zeros(4))
print(np.zeros((2,2)))

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


In [ ]:
print(np.ones(3))
print(np.ones((2,2)))

[1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [ ]:
print(np.arange(3))
print(np.arange(1,9))
'''
The error in the selected code is a TypeError.
The np.arange() function expects scalar arguments (single numbers) to define the start,
stop, and step of the range. However, in the last line, you provided a tuple (4,4)
which is not a valid argument for np.arange().'''
print(np.arange((4,4)))

[0 1 2]
[1 2 3 4 5 6 7 8]


TypeError: arange: scalar arguments expected instead of a tuple.

In [ ]:
print(np.eye(3))
print(np.eye(4,4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.empty(1))
#np.empty((row,col),dtype=int,float)
print(np.empty((3,3),dtype=int))
print(np.empty((3,3),dtype=float))

[1.82e-321]
[[4607182418800017408                   0                   0]
 [                  0 4607182418800017408                   0]
 [                  0                   0 4607182418800017408]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#np.full(size,num)
print(np.full(3,3))
#np.full(size,num),othernumber
print(np.full(2,4),6)
#print in matrix form
#np.full((row,col),num in matrix)
print(np.full((3,4),3))

[3 3 3]
[4 4] 6
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [ ]:
print(np.identity(3))#3X3 matrix form
#equivalent to np.eye(N)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.ones_like(3))
print(np.ones_like((2,2)))

1
[1 1]


In [ ]:
print(np.empty_like(5))
print(np.empty_like((3,3),dtype=int))
print(np.empty_like((3,3),dtype=float))

0
[3 3]
[1.5e-323 1.5e-323]


In [ ]:
print(np.full_like(3,3))
print(np.full_like(2,4),6)
print(np.full_like((5,5),5))

3
4 6
[5 5]


In [ ]:
#it is similar to range()
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


np.sin(),np.cos(),np.tan(),np.arccos(),np.arcsin(),np.arctan(),np.log(),np.log10(),np.log2(),np.e(),

In [ ]:
print(math.pow(np.e,0.2867))
print(np.log(math.pow(np.e,0.2867)))

1.3320245461647273
0.2867


In [ ]:
#np.linespace(start,end,size)
print(np.linspace(0,5,5))
print(np.linspace([1,4],[3,6],5,axis=1))

[0.   1.25 2.5  3.75 5.  ]
[[1.  1.5 2.  2.5 3. ]
 [4.  4.5 5.  5.5 6. ]]


In [ ]:
print(np.log(10))
print(np.log10(10))
print(np.log2(10))

print(np.logspace(0,3,5))
print(np.logspace(0,3,5,base=2))

2.302585092994046
1.0
3.321928094887362
[   1.            5.62341325   31.6227766   177.827941   1000.        ]
[1.         1.68179283 2.82842712 4.75682846 8.        ]


In [ ]:
print(np.geomspace(1,10,3))

[ 1.          3.16227766 10.        ]


In [ ]:
print(np.sin(10))
print(np.cos(10))
print(np.tan(10))

-0.5440211108893698
-0.8390715290764524
0.6483608274590866


In [ ]:
print(np.arccos(10))
print(np.arcsin(10))
print(np.arctan(10))

nan
nan
1.4711276743037347


/tmp/ipython-input-4255526255.py:1: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(10))
/tmp/ipython-input-4255526255.py:2: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(10))


np.add(),np.subtract(),np.mul(),np.div(),np.floor_div(),np.floor(),

In [ ]:
data=np.random.randint(0,10,10)
data

array([4, 0, 4, 4, 3, 5, 7, 3, 9, 1])

In [ ]:
print(data>5)
print(data[data>5])
print(data[data<=np.mean(data)])

[False False False False False False  True False  True False]
[7 9]
[4 0 4 4 3 3 1]


## array manipulation ###
var.T,var.reshape(row,col),np.hstack(),np.vstack(),np.split(),np.hsplit(),np.vsplit(),

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [5]:
print(arr.reshape(3, 2))

[[1 2]
 [3 4]
 [5 6]]


In [6]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [7]:
print(np.hstack((arr, arr2)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [8]:
print(np.vstack((arr, arr2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
print(np.split(arr, 2))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [10]:
print(np.hsplit(arr, 3))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [11]:
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(np.vsplit(arr3, 2))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
